# Generated by Django 4.2.2 on 2025-11-21 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255, null=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='No Title')),
                ('description', models.TextField(default='No Description / (N/A)', null=True)),
                ('file_location', models.FileField(upload_to='papers')),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField(null=True)),
                ('similar_sample', models.TextField(null=True)),
                ('plagiarized', models.BooleanField(default=False)),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.research')),
            ],
        ),
        migrations.CreateModel(
            name='Credibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('title', models.TextField(default='No Title')),
                ('description', models.TextField(default='No Description / (N/A)', null=True)),
                ('file_location', models.FileField(null=True, upload_to='reviewed_papers')),
                ('plagiarism_level', models.FloatField(default=0.0)),
                ('is_plagirized', models.BooleanField(default=False)),
                ('is_pdf', models.BooleanField(default=True)),
                ('remarks', models.TextField(default=None)),
                ('non_pdf_text', models.TextField(default=None, null=True)),
                ('complaint_id', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('person', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.person')),
            ],
        ),
    ]
